In [1]:
import pandas as pd

In [2]:
df=pd.read_excel(r"C:\Users\DELL\Desktop\Admit SLU Rest world.xlsx")

In [3]:
df

,Application: Application ID,Applicant First Name,Applicant Last Name,Applicant: Major,Primary Phone Number,Applicant: Date Application Started,Major,MailingStreet,Mailing Street 2,MailingCity,MailingCountry,Applicant: Mailing Zip/Postal Code,Scholarship Value,Applicant: Date Deferred,Admissions Status,Term
0,App ID-4615373,Moukuri,Mohim,MBA - Professional,1883982526,7/14/2022,MBA - Professional,Road-4 House -621 Section -7 Mirpur Dhaka 1216,NaN,Dhaka,Bangladesh,1216,"$7,000",NaN,Admit,Spring 2023
1,App ID-4620926,Md. Hossain,Khan,MBA - Professional,1710844300,2022-04-08 00:00:00,MBA - Professional,"HOUSE-181-1-C, RAB3, BORO MOGHBAZAR,",NaN,DHAKA,Bangladesh,1217,"$4,000",NaN,Admit,Spring 2023
2,App ID-4682918,Naiem,Mahadi,Supply Chain Management - MS,1554454009,8/15/2022,Supply Chain Management - MS,"2nd Floor, Hazi Nijam Uddin Tower, East Boxnogor,","Sarulia, Demra,",Dhaka,Bangladesh,"1361,","$7,000",NaN,Admit,Spring 2023
3,App ID-4695373,Siyamul Huda,Kabyo,Master of Science in Cybersecurity (On-Campus),1890317920,8/25/2022,Master of Science in Cybersecurity (On-Campus),"#63 Matikata, Matikata Bazar",NaN,Dhaka,Bangladesh,1206,"$6,000",NaN,Admit,Spring 2023
4,App ID-4697239,Rakib,Ahmed,Supply Chain Management - MS,1911356577,2022-01-09 00:00:00,Supply Chain Management - MS,12/B SAYED AWLAD HOSSAIN LANE,ISLAMPUR,DHAKA,Bangladesh,1100,"$5,500",NaN,Admit,Spring 2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141,App ID-4488642,Akbar,Abdurakhmonov,Supply Chain Management - MS,998351785,2/26/2022,Supply Chain Management - MS,S.Darboza 4b/71,Shayhantohur district,Tashkent,Uzbekistan,100021,"$8,000",NaN,Admit,Spring 2023
142,App ID-4592097,Otabek,Nurmukhamedov,Applied Financial Economics - MS,998044993,5/17/2022,Applied Financial Economics - MS,uzbekistan,NaN,tashkent city,Uzbekistan,100187,"$6,000",NaN,Admit,Spring 2023
143,App ID-4722969,Sardorjon,Hasanov,Supply Chain Management - MS,990540571,9/27/2022,Supply Chain Management - MS,Khujakhurasan 4/1,NaN,Shakhrisabz,Uzbekistan,181300,"$5,000",NaN,Admit,Spring 2023
144,App ID-4492982,Edwin,Muchechetere,Master of Science in Cybersecurity (On-Campus),778820923,3/31/2022,Master of Science in Cybersecurity (On-Campus),House No 53,"Rivermead Road, Iven",Gweru,Zimbabwe,NaN,"$6,000",NaN,Admit,Spring 2023
145,App ID-4687962,Praise,Moyo,Master of Science in Bioinformatics and Comput...,263719220109,8/18/2022,Master of Science in Bioinformatics and Comput...,Stand No. 436,436 Mtausi Park,Gweru,Zimbabwe,263,"$4,500",NaN,Admit,Spring 2023

In [4]:
df.head()

,Application: Application ID,Applicant First Name,Applicant Last Name,Applicant: Major,Primary Phone Number,Applicant: Date Application Started,Major,MailingStreet,Mailing Street 2,MailingCity,MailingCountry,Applicant: Mailing Zip/Postal Code,Scholarship Value,Applicant: Date Deferred,Admissions Status,Term
0,App ID-4615373,Moukuri,Mohim,MBA - Professional,1883982526,7/14/2022,MBA - Professional,Road-4 House -621 Section -7 Mirpur Dhaka 1216,NaN,Dhaka,Bangladesh,1216,"$7,000",NaN,Admit,Spring 2023
1,App ID-4620926,Md. Hossain,Khan,MBA - Professional,1710844300,2022-04-08 00:00:00,MBA - Professional,"HOUSE-181-1-C, RAB3, BORO MOGHBAZAR,",NaN,DHAKA,Bangladesh,1217,"$4,000",NaN,Admit,Spring 2023
2,App ID-4682918,Naiem,Mahadi,Supply Chain Management - MS,1554454009,8/15/2022,Supply Chain Management - MS,"2nd Floor, Hazi Nijam Uddin Tower, East Boxnogor,","Sarulia, Demra,",Dhaka,Bangladesh,"1361,","$7,000",NaN,Admit,Spring 2023
3,App ID-4695373,Siyamul Huda,Kabyo,Master of Science in Cybersecurity (On-Campus),1890317920,8/25/2022,Master of Science in Cybersecurity (On-Campus),"#63 Matikata, Matikata Bazar",NaN,Dhaka,Bangladesh,1206,"$6,000",NaN,Admit,Spring 2023
4,App ID-4697239,Rakib,Ahmed,Supply Chain Management - MS,1911356577,2022-01-09 00:00:00,Supply Chain Management - MS,12/B SAYED AWLAD HOSSAIN LANE,ISLAMPUR,DHAKA,Bangladesh,1100,"$5,500",NaN,Admit,Spring 2023

In [5]:
df.shape

(146, 16)

In [6]:
df.tail()

,Application: Application ID,Applicant First Name,Applicant Last Name,Applicant: Major,Primary Phone Number,Applicant: Date Application Started,Major,MailingStreet,Mailing Street 2,MailingCity,MailingCountry,Applicant: Mailing Zip/Postal Code,Scholarship Value,Applicant: Date Deferred,Admissions Status,Term
141,App ID-4488642,Akbar,Abdurakhmonov,Supply Chain Management - MS,998351785,2/26/2022,Supply Chain Management - MS,S.Darboza 4b/71,Shayhantohur district,Tashkent,Uzbekistan,100021,"$8,000",NaN,Admit,Spring 2023
142,App ID-4592097,Otabek,Nurmukhamedov,Applied Financial Economics - MS,998044993,5/17/2022,Applied Financial Economics - MS,uzbekistan,NaN,tashkent city,Uzbekistan,100187,"$6,000",NaN,Admit,Spring 2023
143,App ID-4722969,Sardorjon,Hasanov,Supply Chain Management - MS,990540571,9/27/2022,Supply Chain Management - MS,Khujakhurasan 4/1,NaN,Shakhrisabz,Uzbekistan,181300,"$5,000",NaN,Admit,Spring 2023
144,App ID-4492982,Edwin,Muchechetere,Master of Science in Cybersecurity (On-Campus),778820923,3/31/2022,Master of Science in Cybersecurity (On-Campus),House No 53,"Rivermead Road, Iven",Gweru,Zimbabwe,NaN,"$6,000",NaN,Admit,Spring 2023
145,App ID-4687962,Praise,Moyo,Master of Science in Bioinformatics and Comput...,263719220109,8/18/2022,Master of Science in Bioinformatics and Comput...,Stand No. 436,436 Mtausi Park,Gweru,Zimbabwe,263,"$4,500",NaN,Admit,Spring 2023

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 146 entries, 0 to 145
Data columns (total 16 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Application: Application ID          146 non-null    object
 1   Applicant First Name                 146 non-null    object
 2   Applicant Last Name                  146 non-null    object
 3   Applicant: Major                     146 non-null    object
 4   Primary Phone Number                 146 non-null    object
 5   Applicant: Date Application Started  146 non-null    object
 6   Major                                146 non-null    object
 7   MailingStreet                        146 non-null    object
 8   Mailing Street 2                     42 non-null     object
 9   MailingCity                          146 non-null    object
 10  MailingCountry                       146 non-null    object
 11  Applicant: Mailing Zip/Postal Code   119 non-null    object
 12  Scholarship Value                    127 non-null    object
 13  Applicant: Date Deferred             4 non-null      object
 14  Admissions Status                    146 non-null    object
 15  Term                                 146 non-null    object
dtypes: object(16)
memory usage: 18.4+ KB

In [8]:
df.describe()

,Application: Application ID,Applicant First Name,Applicant Last Name,Applicant: Major,Primary Phone Number,Applicant: Date Application Started,Major,MailingStreet,Mailing Street 2,MailingCity,MailingCountry,Applicant: Mailing Zip/Postal Code,Scholarship Value,Applicant: Date Deferred,Admissions Status,Term
count,146,146,146,146,146,146,146,146,42,146,146,119,127,4,146,146
unique,146,138,142,18,145,106,18,145,41,106,24,89,22,3,1,3
top,App ID-4615373,Michael,Khan,Applied Financial Economics - MS,544491668,2022-08-08 00:00:00,Applied Financial Economics - MS,"Post Office Box KN1739, Kaneshie, Accra-Ghana.","Opposite Pentecost university main campus, Acc...",Lagos,Nigeria,233,"$6,000",2022-01-08 00:00:00,Admit,Spring 2023
freq,1,3,3,23,2,4,23,2,2,9,53,12,18,2,146,111

In [9]:
df['MailingStreet']

0         Road-4 House -621 Section -7 Mirpur Dhaka 1216
1                   HOUSE-181-1-C, RAB3, BORO MOGHBAZAR,
2      2nd Floor, Hazi Nijam Uddin Tower, East Boxnogor,
3                           #63 Matikata, Matikata Bazar
4                          12/B SAYED AWLAD HOSSAIN LANE
                             ...
141                                      S.Darboza 4b/71
142                                           uzbekistan
143                                    Khujakhurasan 4/1
144                                          House No 53
145                                        Stand No. 436
Name: MailingStreet, Length: 146, dtype: object

In [10]:
df['MailingCity']

0              Dhaka
1              DHAKA
2              Dhaka
3              Dhaka
4              DHAKA
           ...
141         Tashkent
142    tashkent city
143      Shakhrisabz
144            Gweru
145            Gweru
Name: MailingCity, Length: 146, dtype: object

In [11]:
df['MailingCountry']

0      Bangladesh
1      Bangladesh
2      Bangladesh
3      Bangladesh
4      Bangladesh
          ...
141    Uzbekistan
142    Uzbekistan
143    Uzbekistan
144      Zimbabwe
145      Zimbabwe
Name: MailingCountry, Length: 146, dtype: object

In [12]:
df['MailingCountry'].value_counts()

Nigeria                 53
Ghana                   30
Pakistan                11
United States            6
Nepal                    6
Bangladesh               5
Liberia                  4
Ethiopia                 3
Uzbekistan               3
China                    3
South Korea              3
Russia                   2
United Arab Emirates     2
Taiwan                   2
Zimbabwe                 2
Cameroon                 2
Kenya                    2
Iran                     1
Romania                  1
Botswana                 1
Uganda                   1
United Kingdom           1
Cambodia                 1
Saudi Arabia             1
Name: MailingCountry, dtype: int64

In [13]:
df

,Application: Application ID,Applicant First Name,Applicant Last Name,Applicant: Major,Primary Phone Number,Applicant: Date Application Started,Major,MailingStreet,Mailing Street 2,MailingCity,MailingCountry,Applicant: Mailing Zip/Postal Code,Scholarship Value,Applicant: Date Deferred,Admissions Status,Term
0,App ID-4615373,Moukuri,Mohim,MBA - Professional,1883982526,7/14/2022,MBA - Professional,Road-4 House -621 Section -7 Mirpur Dhaka 1216,NaN,Dhaka,Bangladesh,1216,"$7,000",NaN,Admit,Spring 2023
1,App ID-4620926,Md. Hossain,Khan,MBA - Professional,1710844300,2022-04-08 00:00:00,MBA - Professional,"HOUSE-181-1-C, RAB3, BORO MOGHBAZAR,",NaN,DHAKA,Bangladesh,1217,"$4,000",NaN,Admit,Spring 2023
2,App ID-4682918,Naiem,Mahadi,Supply Chain Management - MS,1554454009,8/15/2022,Supply Chain Management - MS,"2nd Floor, Hazi Nijam Uddin Tower, East Boxnogor,","Sarulia, Demra,",Dhaka,Bangladesh,"1361,","$7,000",NaN,Admit,Spring 2023
3,App ID-4695373,Siyamul Huda,Kabyo,Master of Science in Cybersecurity (On-Campus),1890317920,8/25/2022,Master of Science in Cybersecurity (On-Campus),"#63 Matikata, Matikata Bazar",NaN,Dhaka,Bangladesh,1206,"$6,000",NaN,Admit,Spring 2023
4,App ID-4697239,Rakib,Ahmed,Supply Chain Management - MS,1911356577,2022-01-09 00:00:00,Supply Chain Management - MS,12/B SAYED AWLAD HOSSAIN LANE,ISLAMPUR,DHAKA,Bangladesh,1100,"$5,500",NaN,Admit,Spring 2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141,App ID-4488642,Akbar,Abdurakhmonov,Supply Chain Management - MS,998351785,2/26/2022,Supply Chain Management - MS,S.Darboza 4b/71,Shayhantohur district,Tashkent,Uzbekistan,100021,"$8,000",NaN,Admit,Spring 2023
142,App ID-4592097,Otabek,Nurmukhamedov,Applied Financial Economics - MS,998044993,5/17/2022,Applied Financial Economics - MS,uzbekistan,NaN,tashkent city,Uzbekistan,100187,"$6,000",NaN,Admit,Spring 2023
143,App ID-4722969,Sardorjon,Hasanov,Supply Chain Management - MS,990540571,9/27/2022,Supply Chain Management - MS,Khujakhurasan 4/1,NaN,Shakhrisabz,Uzbekistan,181300,"$5,000",NaN,Admit,Spring 2023
144,App ID-4492982,Edwin,Muchechetere,Master of Science in Cybersecurity (On-Campus),778820923,3/31/2022,Master of Science in Cybersecurity (On-Campus),House No 53,"Rivermead Road, Iven",Gweru,Zimbabwe,NaN,"$6,000",NaN,Admit,Spring 2023
145,App ID-4687962,Praise,Moyo,Master of Science in Bioinformatics and Comput...,263719220109,8/18/2022,Master of Science in Bioinformatics and Comput...,Stand No. 436,436 Mtausi Park,Gweru,Zimbabwe,263,"$4,500",NaN,Admit,Spring 2023

In [14]:
new=df.drop(['Application: Application ID', 'Applicant First Name','Applicant Last Name', 'Applicant: Major', 'Primary Phone Number', 'Applicant: Date Application Started', 'Major','Scholarship Value','Applicant: Date Deferred','Admissions Status','Term'], axis=1)

In [15]:
new

,MailingStreet,Mailing Street 2,MailingCity,MailingCountry,Applicant: Mailing Zip/Postal Code
0,Road-4 House -621 Section -7 Mirpur Dhaka 1216,NaN,Dhaka,Bangladesh,1216
1,"HOUSE-181-1-C, RAB3, BORO MOGHBAZAR,",NaN,DHAKA,Bangladesh,1217
2,"2nd Floor, Hazi Nijam Uddin Tower, East Boxnogor,","Sarulia, Demra,",Dhaka,Bangladesh,"1361,"
3,"#63 Matikata, Matikata Bazar",NaN,Dhaka,Bangladesh,1206
4,12/B SAYED AWLAD HOSSAIN LANE,ISLAMPUR,DHAKA,Bangladesh,1100
...,...,...,...,...,...
141,S.Darboza 4b/71,Shayhantohur district,Tashkent,Uzbekistan,100021
142,uzbekistan,NaN,tashkent city,Uzbekistan,100187
143,Khujakhurasan 4/1,NaN,Shakhrisabz,Uzbekistan,181300
144,House No 53,"Rivermead Road, Iven",Gweru,Zimbabwe,NaN
145,Stand No. 436,436 Mtausi Park,Gweru,Zimbabwe,263

In [16]:
df['MailingCountry'].value_counts()

Nigeria                 53
Ghana                   30
Pakistan                11
United States            6
Nepal                    6
Bangladesh               5
Liberia                  4
Ethiopia                 3
Uzbekistan               3
China                    3
South Korea              3
Russia                   2
United Arab Emirates     2
Taiwan                   2
Zimbabwe                 2
Cameroon                 2
Kenya                    2
Iran                     1
Romania                  1
Botswana                 1
Uganda                   1
United Kingdom           1
Cambodia                 1
Saudi Arabia             1
Name: MailingCountry, dtype: int64

In [17]:
new

,MailingStreet,Mailing Street 2,MailingCity,MailingCountry,Applicant: Mailing Zip/Postal Code
0,Road-4 House -621 Section -7 Mirpur Dhaka 1216,NaN,Dhaka,Bangladesh,1216
1,"HOUSE-181-1-C, RAB3, BORO MOGHBAZAR,",NaN,DHAKA,Bangladesh,1217
2,"2nd Floor, Hazi Nijam Uddin Tower, East Boxnogor,","Sarulia, Demra,",Dhaka,Bangladesh,"1361,"
3,"#63 Matikata, Matikata Bazar",NaN,Dhaka,Bangladesh,1206
4,12/B SAYED AWLAD HOSSAIN LANE,ISLAMPUR,DHAKA,Bangladesh,1100
...,...,...,...,...,...
141,S.Darboza 4b/71,Shayhantohur district,Tashkent,Uzbekistan,100021
142,uzbekistan,NaN,tashkent city,Uzbekistan,100187
143,Khujakhurasan 4/1,NaN,Shakhrisabz,Uzbekistan,181300
144,House No 53,"Rivermead Road, Iven",Gweru,Zimbabwe,NaN
145,Stand No. 436,436 Mtausi Park,Gweru,Zimbabwe,263

In [18]:
new.head()

,MailingStreet,Mailing Street 2,MailingCity,MailingCountry,Applicant: Mailing Zip/Postal Code
0,Road-4 House -621 Section -7 Mirpur Dhaka 1216,NaN,Dhaka,Bangladesh,1216
1,"HOUSE-181-1-C, RAB3, BORO MOGHBAZAR,",NaN,DHAKA,Bangladesh,1217
2,"2nd Floor, Hazi Nijam Uddin Tower, East Boxnogor,","Sarulia, Demra,",Dhaka,Bangladesh,"1361,"
3,"#63 Matikata, Matikata Bazar",NaN,Dhaka,Bangladesh,1206
4,12/B SAYED AWLAD HOSSAIN LANE,ISLAMPUR,DHAKA,Bangladesh,1100

In [19]:
new.tail()

,MailingStreet,Mailing Street 2,MailingCity,MailingCountry,Applicant: Mailing Zip/Postal Code
141,S.Darboza 4b/71,Shayhantohur district,Tashkent,Uzbekistan,100021
142,uzbekistan,NaN,tashkent city,Uzbekistan,100187
143,Khujakhurasan 4/1,NaN,Shakhrisabz,Uzbekistan,181300
144,House No 53,"Rivermead Road, Iven",Gweru,Zimbabwe,NaN
145,Stand No. 436,436 Mtausi Park,Gweru,Zimbabwe,263

In [20]:
new.shape

(146, 5)

In [21]:
new.head(10)

,MailingStreet,Mailing Street 2,MailingCity,MailingCountry,Applicant: Mailing Zip/Postal Code
0,Road-4 House -621 Section -7 Mirpur Dhaka 1216,NaN,Dhaka,Bangladesh,1216
1,"HOUSE-181-1-C, RAB3, BORO MOGHBAZAR,",NaN,DHAKA,Bangladesh,1217
2,"2nd Floor, Hazi Nijam Uddin Tower, East Boxnogor,","Sarulia, Demra,",Dhaka,Bangladesh,"1361,"
3,"#63 Matikata, Matikata Bazar",NaN,Dhaka,Bangladesh,1206
4,12/B SAYED AWLAD HOSSAIN LANE,ISLAMPUR,DHAKA,Bangladesh,1100
5,P O BOX 70854,NaN,Gaborone,Botswana,0
6,St.109 Sangkat Mittapheap Khan 7 Makara Phnom ...,NaN,Phnom Penh,Cambodia,NaN
7,O12,12,DOUALA,Cameroon,237
8,Quarter 03,Full Gospel Road Likomba,Tiko,Cameroon,333 Tiko
9,381 Yuanbin East Road,Xianyou County,Putian,China,351200

In [22]:
new.dropna(subset=["Applicant: Mailing Zip/Postal Code"], inplace=True)

In [23]:
new['MailingStreet']

0         Road-4 House -621 Section -7 Mirpur Dhaka 1216
1                   HOUSE-181-1-C, RAB3, BORO MOGHBAZAR,
2      2nd Floor, Hazi Nijam Uddin Tower, East Boxnogor,
3                           #63 Matikata, Matikata Bazar
4                          12/B SAYED AWLAD HOSSAIN LANE
                             ...
140                                       58 fountain st
141                                      S.Darboza 4b/71
142                                           uzbekistan
143                                    Khujakhurasan 4/1
145                                        Stand No. 436
Name: MailingStreet, Length: 119, dtype: object

In [24]:
new['Mailing Street 2']

0                        NaN
1                        NaN
2            Sarulia, Demra,
3                        NaN
4                   ISLAMPUR
               ...
140                     #204
141    Shayhantohur district
142                      NaN
143                      NaN
145          436 Mtausi Park
Name: Mailing Street 2, Length: 119, dtype: object

In [25]:
new['MailingCountry']

0         Bangladesh
1         Bangladesh
2         Bangladesh
3         Bangladesh
4         Bangladesh
           ...
140    United States
141       Uzbekistan
142       Uzbekistan
143       Uzbekistan
145         Zimbabwe
Name: MailingCountry, Length: 119, dtype: object

In [26]:
new

,MailingStreet,Mailing Street 2,MailingCity,MailingCountry,Applicant: Mailing Zip/Postal Code
0,Road-4 House -621 Section -7 Mirpur Dhaka 1216,NaN,Dhaka,Bangladesh,1216
1,"HOUSE-181-1-C, RAB3, BORO MOGHBAZAR,",NaN,DHAKA,Bangladesh,1217
2,"2nd Floor, Hazi Nijam Uddin Tower, East Boxnogor,","Sarulia, Demra,",Dhaka,Bangladesh,"1361,"
3,"#63 Matikata, Matikata Bazar",NaN,Dhaka,Bangladesh,1206
4,12/B SAYED AWLAD HOSSAIN LANE,ISLAMPUR,DHAKA,Bangladesh,1100
...,...,...,...,...,...
140,58 fountain st,#204,New Haven,United States,6515
141,S.Darboza 4b/71,Shayhantohur district,Tashkent,Uzbekistan,100021
142,uzbekistan,NaN,tashkent city,Uzbekistan,100187
143,Khujakhurasan 4/1,NaN,Shakhrisabz,Uzbekistan,181300
145,Stand No. 436,436 Mtausi Park,Gweru,Zimbabwe,263

In [27]:
new.drop_duplicates()

,MailingStreet,Mailing Street 2,MailingCity,MailingCountry,Applicant: Mailing Zip/Postal Code
0,Road-4 House -621 Section -7 Mirpur Dhaka 1216,NaN,Dhaka,Bangladesh,1216
1,"HOUSE-181-1-C, RAB3, BORO MOGHBAZAR,",NaN,DHAKA,Bangladesh,1217
2,"2nd Floor, Hazi Nijam Uddin Tower, East Boxnogor,","Sarulia, Demra,",Dhaka,Bangladesh,"1361,"
3,"#63 Matikata, Matikata Bazar",NaN,Dhaka,Bangladesh,1206
4,12/B SAYED AWLAD HOSSAIN LANE,ISLAMPUR,DHAKA,Bangladesh,1100
...,...,...,...,...,...
140,58 fountain st,#204,New Haven,United States,6515
141,S.Darboza 4b/71,Shayhantohur district,Tashkent,Uzbekistan,100021
142,uzbekistan,NaN,tashkent city,Uzbekistan,100187
143,Khujakhurasan 4/1,NaN,Shakhrisabz,Uzbekistan,181300
145,Stand No. 436,436 Mtausi Park,Gweru,Zimbabwe,263

In [28]:
new.info
new.reset_index(drop=True, inplace=True)

In [29]:
new.to_csv("New Updated Address1")

In [30]:
import csv

In [31]:
with open(r"C:\Users\DELL\Desktop\New Updated Address1") as file_obj:
    reader_obj=csv.reader(file_obj)
    for row in reader_obj:
        print(row)

['', 'MailingStreet', 'Mailing Street 2', 'MailingCity', 'MailingCountry', 'Applicant: Mailing Zip/Postal Code']
['0', '2nd Floor, Hazi Nijam Uddin Tower, East Boxnogor,', 'Sarulia, Demra,', 'Dhaka', 'Bangladesh', '1361,']
['1', '12/B SAYED AWLAD HOSSAIN LANE', 'ISLAMPUR', 'DHAKA', 'Bangladesh', '1100']
['2', 'O12', '12', 'DOUALA', 'Cameroon', '237']
['3', 'Quarter 03', 'Full Gospel Road Likomba', 'Tiko', 'Cameroon', '333 Tiko']
['4', '381 Yuanbin East Road', 'Xianyou County', 'Putian', 'China', '351200']
['5', 'Taiyuan University of Technology', 'No 79 West Yingze, Wanbailin District', 'Taiyuan', 'China', '30024']
['6', 'Ras Abebe Aregayi', 'Ras Abebe Aregay', 'Addis Ababa', 'Ethiopia', '9568']
['7', '2/1STATEMENT CLOSE. KOJOKROM.', 'POST OFFICE BX TD 832. TAKORADI.', 'SEKONDI', 'Ghana', '233']
['8', 'Digital address: Z227 Fork St, CX-082-5908', 'Fork St, Cx-082-590', 'Kasoa', 'Ghana', 'OK 39, KASOA']
['9', 'Plot 20 Block P', 'Gyinyase', 'Kumasi', 'Ghana', 'AK-442-6863']
['10', 'Ongata Rongai', 'Bogani Road', 'Nairobi', 'Kenya', '100']
['11', 'Johnson Street', 'Slipway', 'Monrovia', 'Liberia', '1000']
['12', 'Newroad', 'Kaski', 'Pokhara', 'Nepal', '33700']
['13', '2 Akinyele Close, Iju-Station,Agege, Lagos', '2 Akinyele Close, Iju-Station, Agege, Lagos', 'Lagos', 'Nigeria', '100216']
['14', '29 Adewale Adegbosin Street', 'Ajah', 'Lagos', 'Nigeria', '101245']
['15', 'Oba Elegushi Housing Estate Ilaje 6', 'Oba Elegushi Housing Estate, Ilaje, 6', 'Ajah', 'Nigeria', '102266']
['16', '13', 'Oba Yekini Road', 'Elegushi Lekki', 'Nigeria', '23401']
['17', '18', 'ASSO- LAND CRESCENT', 'AGBEDE , IKORODU', 'Nigeria', '23401']
['18', '5B LUKMAN LAWAL STREET, AREA 1 ESTATE ALAGBADO', 'ALAGBADO LAGOS', 'ALAGBADO', 'Nigeria', '10000001']
['19', '4b Akanbi Arimi street Aguda surulere', '4b Akanbi Arimi street, Aguda surulere', 'Lagos', 'Nigeria', '234000']
['20', 'Fanisau quarters Hadejia Jigawa State', 'Hausari Nguru', 'Hadejia', 'Nigeria', '731102']
['21', '12', 'Ojulowo Imoshe Anifowoshe', 'Ikeja', 'Nigeria', '100271']
['22', 'No 28 obadan street,off new agbor road,uromi.', 'no 28 0badan street,off new agbor road,uromi', 'uromi', 'Nigeria', 'PMB 36']
['23', 'Plot 495b Fatai Lapade Street,', 'Omole Phase 2 Estate', 'Lagos', 'Nigeria', '105102']
['24', '5 Adeyemi close Iju Ajuwon Lagos', 'Lagos Nigeria', 'Iju Ajuwon', 'Nigeria', '100011']
['25', '41 Road B Close Block 1 Flat 7', 'House 7', 'Festac Town', 'Nigeria', '23401']
['26', 'MASHA ALLAH BARRACKS ROAD, JIMETA ADAMAWA', 'MASHA ALLAH BARRACKS ROAD, JIMETA', 'YOLA', 'Nigeria', '23401']
['27', 'Mohalla rehm pura hassan abdal distt attock punjab pakistan', 'No', 'Hassan abdal', 'Pakistan', '43730']
['28', 'Apartment 8, Building 10', 'Ibrahim Al Maqdessi Street, Al Malaz', 'Riyadh', 'Saudi Arabia', '12584/12546']
['29', '101-804, Jibongro 21 Road 19', 'Sungbuk-Gu', 'Seoul', 'South Korea', '2870']
['30', '3140, Grand Pavilion Unit 203', '3140, Grand Pavilion, Unit 203', 'Tampa', 'United States', '33613']
['31', '1700 E 12Th St', '#7O', 'Cleveland', 'United States', '44114']
['32', '58 fountain st', '#204', 'New Haven', 'United States', '6515']
['33', 'S.Darboza 4b/71', 'Shayhantohur district', 'Tashkent', 'Uzbekistan', '100021']
['34', 'Stand No. 436', '436 Mtausi Park', 'Gweru', 'Zimbabwe', '263']

In [32]:
df=pd.read_csv(r"C:\Users\DELL\Desktop\New Updated Address1")
df

,Unnamed: 0,MailingStreet,Mailing Street 2,MailingCity,MailingCountry,Applicant: Mailing Zip/Postal Code
0,0,"2nd Floor, Hazi Nijam Uddin Tower, East Boxnogor,","Sarulia, Demra,",Dhaka,Bangladesh,"1361,"
1,1,12/B SAYED AWLAD HOSSAIN LANE,ISLAMPUR,DHAKA,Bangladesh,1100
2,2,O12,12,DOUALA,Cameroon,237
3,3,Quarter 03,Full Gospel Road Likomba,Tiko,Cameroon,333 Tiko
4,4,381 Yuanbin East Road,Xianyou County,Putian,China,351200
5,5,Taiyuan University of Technology,"No 79 West Yingze, Wanbailin District",Taiyuan,China,30024
6,6,Ras Abebe Aregayi,Ras Abebe Aregay,Addis Ababa,Ethiopia,9568
7,7,2/1STATEMENT CLOSE. KOJOKROM.,POST OFFICE BX TD 832. TAKORADI.,SEKONDI,Ghana,233
8,8,"Digital address: Z227 Fork St, CX-082-5908","Fork St, Cx-082-590",Kasoa,Ghana,"OK 39, KASOA"
9,9,Plot 20 Block P,Gyinyase,Kumasi,Ghana,AK-442-6863
10,10,Ongata Rongai,Bogani Road,Nairobi,Kenya,100
11,11,Johnson Street,Slipway,Monrovia,Liberia,1000
12,12,Newroad,Kaski,Pokhara,Nepal,33700
13,13,"2 Akinyele Close, Iju-Station,Agege, Lagos","2 Akinyele Close, Iju-Station, Agege, Lagos",Lagos,Nigeria,100216
14,14,29 Adewale Adegbosin Street,Ajah,Lagos,Nigeria,101245
15,15,Oba Elegushi Housing Estate Ilaje 6,"Oba Elegushi Housing Estate, Ilaje, 6",Ajah,Nigeria,102266
16,16,13,Oba Yekini Road,Elegushi Lekki,Nigeria,23401
17,17,18,ASSO- LAND CRESCENT,"AGBEDE , IKORODU",Nigeria,23401
18,18,"5B LUKMAN LAWAL STREET, AREA 1 ESTATE ALAGBADO",ALAGBADO LAGOS,ALAGBADO,Nigeria,10000001
19,19,4b Akanbi Arimi street Aguda surulere,"4b Akanbi Arimi street, Aguda surulere",Lagos,Nigeria,234000
20,20,Fanisau quarters Hadejia Jigawa State,Hausari Nguru,Hadejia,Nigeria,731102
21,21,12,Ojulowo Imoshe Anifowoshe,Ikeja,Nigeria,100271
22,22,"No 28 obadan street,off new agbor road,uromi.","no 28 0badan street,off new agbor road,uromi",uromi,Nigeria,PMB 36
23,23,"Plot 495b Fatai Lapade Street,",Omole Phase 2 Estate,Lagos,Nigeria,105102
24,24,5 Adeyemi close Iju Ajuwon Lagos,Lagos Nigeria,Iju Ajuwon,Nigeria,100011
25,25,41 Road B Close Block 1 Flat 7,House 7,Festac Town,Nigeria,23401
26,26,"MASHA ALLAH BARRACKS ROAD, JIMETA ADAMAWA","MASHA ALLAH BARRACKS ROAD, JIMETA",YOLA,Nigeria,23401
27,27,Mohalla rehm pura hassan abdal distt attock pu...,No,Hassan abdal,Pakistan,43730
28,28,"Apartment 8, Building 10","Ibrahim Al Maqdessi Street, Al Malaz",Riyadh,Saudi Arabia,12584/12546
29,29,"101-804, Jibongro 21 Road 19",Sungbuk-Gu,Seoul,South Korea,2870
30,30,"3140, Grand Pavilion Unit 203","3140, Grand Pavilion, Unit 203",Tampa,United States,33613
31,31,1700 E 12Th St,#7O,Cleveland,United States,44114
32,32,58 fountain st,#204,New Haven,United States,6515
33,33,S.Darboza 4b/71,Shayhantohur district,Tashkent,Uzbekistan,100021
34,34,Stand No. 436,436 Mtausi Park,Gweru,Zimbabwe,263

In [33]:
df["MailingStreet"]=df["MailingStreet"] + "," + df["Mailing Street 2"] +"," + df["MailingCity"] + "," + df["MailingCountry"]
df["MailingStreet"]

0     2nd Floor, Hazi Nijam Uddin Tower, East Boxnog...
1     12/B SAYED AWLAD HOSSAIN LANE,ISLAMPUR,DHAKA,B...
2                                O12,12,DOUALA,Cameroon
3     Quarter 03,Full Gospel Road Likomba,Tiko,Cameroon
4     381 Yuanbin East Road,Xianyou County,Putian,China
5     Taiyuan University of Technology,No 79 West Yi...
6     Ras Abebe Aregayi,Ras Abebe Aregay,Addis Ababa...
7     2/1STATEMENT CLOSE. KOJOKROM.,POST OFFICE BX T...
8     Digital address: Z227 Fork St, CX-082-5908,For...
9                 Plot 20 Block P,Gyinyase,Kumasi,Ghana
10              Ongata Rongai,Bogani Road,Nairobi,Kenya
11              Johnson Street,Slipway,Monrovia,Liberia
12                          Newroad,Kaski,Pokhara,Nepal
13    2 Akinyele Close, Iju-Station,Agege, Lagos,2 A...
14       29 Adewale Adegbosin Street,Ajah,Lagos,Nigeria
15    Oba Elegushi Housing Estate Ilaje 6,Oba Elegus...
16            13,Oba Yekini Road,Elegushi Lekki,Nigeria
17      18,ASSO- LAND CRESCENT,AGBEDE , IKORODU,Nigeria
18    5B LUKMAN LAWAL STREET, AREA 1 ESTATE ALAGBADO...
19    4b Akanbi Arimi street Aguda surulere,4b Akanb...
20    Fanisau quarters Hadejia Jigawa State,Hausari ...
21           12,Ojulowo Imoshe Anifowoshe,Ikeja,Nigeria
22    No 28 obadan street,off new agbor road,uromi.,...
23    Plot 495b Fatai Lapade Street,,Omole Phase 2 E...
24    5 Adeyemi close Iju Ajuwon Lagos,Lagos Nigeria...
25    41 Road B Close Block 1 Flat 7,House 7,Festac ...
26    MASHA ALLAH BARRACKS ROAD, JIMETA ADAMAWA,MASH...
27    Mohalla rehm pura hassan abdal distt attock pu...
28    Apartment 8, Building 10,Ibrahim Al Maqdessi S...
29    101-804, Jibongro 21 Road 19,Sungbuk-Gu,Seoul,...
30    3140, Grand Pavilion Unit 203,3140, Grand Pavi...
31           1700 E 12Th St,#7O,Cleveland,United States
32          58 fountain st,#204,New Haven,United States
33    S.Darboza 4b/71,Shayhantohur district,Tashkent...
34         Stand No. 436,436 Mtausi Park,Gweru,Zimbabwe
Name: MailingStreet, dtype: object

In [34]:
from geopy.geocoders import Nominatim
nom= Nominatim(user_agent="jupyter notebook")
n=nom.geocode("Dilshad Garden")

In [35]:
df["Validity"]=df["Mailing Street 2"]+"," +df["MailingCity"]
df["Validity"]

0                                 Sarulia, Demra,,Dhaka
1                                        ISLAMPUR,DHAKA
2                                             12,DOUALA
3                         Full Gospel Road Likomba,Tiko
4                                 Xianyou County,Putian
5         No 79 West Yingze, Wanbailin District,Taiyuan
6                          Ras Abebe Aregay,Addis Ababa
7              POST OFFICE BX TD 832. TAKORADI.,SEKONDI
8                             Fork St, Cx-082-590,Kasoa
9                                       Gyinyase,Kumasi
10                                  Bogani Road,Nairobi
11                                     Slipway,Monrovia
12                                        Kaski,Pokhara
13    2 Akinyele Close, Iju-Station, Agege, Lagos,Lagos
14                                           Ajah,Lagos
15           Oba Elegushi Housing Estate, Ilaje, 6,Ajah
16                       Oba Yekini Road,Elegushi Lekki
17                 ASSO- LAND CRESCENT,AGBEDE , IKORODU
18                              ALAGBADO LAGOS,ALAGBADO
19         4b Akanbi Arimi street, Aguda surulere,Lagos
20                                Hausari Nguru,Hadejia
21                      Ojulowo Imoshe Anifowoshe,Ikeja
22    no 28 0badan street,off new agbor road,uromi,u...
23                           Omole Phase 2 Estate,Lagos
24                             Lagos Nigeria,Iju Ajuwon
25                                  House 7,Festac Town
26               MASHA ALLAH BARRACKS ROAD, JIMETA,YOLA
27                                      No,Hassan abdal
28          Ibrahim Al Maqdessi Street, Al Malaz,Riyadh
29                                     Sungbuk-Gu,Seoul
30                 3140, Grand Pavilion, Unit 203,Tampa
31                                        #7O,Cleveland
32                                       #204,New Haven
33                       Shayhantohur district,Tashkent
34                                436 Mtausi Park,Gweru
Name: Validity, dtype: object

In [36]:
df["Address"]=df["Validity"].apply(nom.geocode)
FinalAddress=df["Address"]

In [37]:
FinalAddress.to_csv("Valid_Address_csv")

In [38]:
valid=pd.read_csv(r"C:\Users\DELL\Desktop\Valid_Address_csv")
valid

    Unnamed: 0                                            Address
0            0                                                NaN
1            1  ইসলামপুর, ঢাকা, ঢাকা মহানগর, ঢাকা জেলা, ঢাকা ব...
2            2  Papa Douala, 12, Avenue Adolphe Demeur - Adolp...
3            3                                                NaN
4            4                                  仙游县, 莆田市, 福建省, 中国
5            5                                                NaN
6            6  Ras Abebe Aregay Street, ለገሐር አካባቢ / Legahar, ...
7            7                                                NaN
8            8                                                NaN
9            9  Kumasi High School, Gyinyase, Kumasi, Kumasi M...
10          10                 Bogani Road, Nairobi, 24722, Kenya
11          11  Slipway Road, Vai Town, Crown Hill, Monrovia, ...
12          12            Pokhara, कास्की, Gandaki Pradesh, नेपाल
13          13                                                NaN
14          14                      Ajah, Eti Osa, Lagos, Nigeria
15          15                                                NaN
16          16                                                NaN
17          17                                                NaN
18          18                                                NaN
19          19                                                NaN
20          20                                                NaN
21          21                                                NaN
22          22                                                NaN
23          23                                                NaN
24          24                                                NaN
25          25  Festac Town, Amuwo Odofin, Lagos, 102102, Nigeria
26          26                                                NaN
27          27  Rue Moulay Abdal Hafid زنقة مولاي عبد الحفيظ, ...
28          28                                                NaN
29          29                                                NaN
30          30                                                NaN
31          31  Cleveland, Ferndale, Royal Tunbridge Wells, Tu...
32          32  204, Scott Road, Prospect, New Haven County, C...
33          33                                                NaN
34          34                                                NaN

In [39]:
valid.isnull().sum()

Unnamed: 0     0
Address       22
dtype: int64

In [40]:
valid.shape

(35, 2)